import assert from 'node:assert/strict'
import test from 'node:test'
import { createPaliroHomeBoxMotion } from '../src/services/paliroHomeBoxMotion.js'

test('entry emits six slots once per session, and departure cancels stale work', (t) => {
  t.mock.timers.enable({ apis: ['setTimeout'] })
  const motion = createPaliroHomeBoxMotion({ reducedMotion: () => false })
  motion.enter()
  assert.equal(motion.phase.value, 'spinning')
  motion.enter()
  t.mock.timers.tick(1000)
  assert.equal(motion.phase.value, 'opening')
  t.mock.timers.tick(500)
  assert.equal(motion.phase.value, 'emitting')
  motion.leave()
  t.mock.timers.tick(4000)
  assert.equal(motion.busy.value, false)
  motion.enter()
  assert.equal(motion.phase.value, 'idle')
  motion.reset()
  motion.enter()
  assert.equal(motion.phase.value, 'spinning')
  motion.dispose()
})

test('Close lands the replacement before shuffling all slots and unlocks after they return', (t) => {
  t.mock.timers.enable({ apis: ['setTimeout'] })
  const motion = createPaliroHomeBoxMotion({ reducedMotion: () => false })
  for (let slot = 0; slot < 6; slot++) {
    motion.refill(slot)
    assert.equal(motion.vacantSlot.value, slot)
    assert.equal(motion.busy.value, true)
    t.mock.timers.tick(500)
    assert.equal(motion.phase.value, 'refill-emitting')
    assert.equal(motion.vacantSlot.value, slot)
    t.mock.timers.tick(900)
    assert.equal(motion.phase.value, 'refill-closing')
    assert.equal(motion.vacantSlot.value, null)
    assert.equal(motion.busy.value, true)
    t.mock.timers.tick(450)
    assert.equal(motion.phase.value, 'refill-shuffling')
    assert.equal(motion.vacantSlot.value, null)
    assert.equal(motion.busy.value, true)
    t.mock.timers.tick(1649)
    assert.equal(motion.busy.value, true)
    t.mock.timers.tick(1)
    assert.equal(motion.busy.value, false)
  }
  motion.dispose()
})

test('reduced motion and cancelled refills never leave a missing box or lock', (t) => {
  t.mock.timers.enable({ apis: ['setTimeout'] })
  const motion = createPaliroHomeBoxMotion({ reducedMotion: () => true })
  motion.enter()
  motion.refill(0)
  assert.equal(motion.vacantSlot.value, null)
  assert.equal(motion.busy.value, false)
  motion.reset()
  assert.equal(motion.introPlayed.value, false)
  const animated = createPaliroHomeBoxMotion({ reducedMotion: () => false })
  animated.enter()
  animated.refill(5)
  t.mock.timers.tick(1850)
  assert.equal(animated.phase.value, 'refill-shuffling')
  animated.leave()
  t.mock.timers.tick(5000)
  assert.equal(animated.phase.value, 'idle')
  assert.equal(animated.vacantSlot.value, null)
  motion.dispose()
  animated.dispose()
})
